language: python
python:
  - "3.7"

install:
  - pip install --upgrade pip
  - pip install pipenv
  - python -m pipenv lock -r > requirements.txt
  - pip install -r requirements.txt

script:
  - pipenv run python -m unittest discover -v -s src -p "*_test.py"

